### ISSUE TITLE
FileProperties class does not appear to be utilitized

### ISSUE THREAD

**Issue by davidpoulos** [nullbucket/edi-debatcher#7]
FileProperties class does not appear to be used other than in a Unit Test. Could this possibly be an attempt to read all delimiters from a properties file, but was left un-finished?

```java
FileProperties.java
```

**Comment by short000** [comment]
I took a quick look: it's residual left behind from pull request #6. I should have also deleted that file and the unit test for that too. Can you remove it? Thanks.
